// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdxFnNMovjpGEhH8pRKa_GVGdTcYLDBn8',
    appId: '1:1030432137825:web:0647ff1d75fc1f408bc020',
    messagingSenderId: '1030432137825',
    projectId: 'ctnrweb',
    authDomain: 'ctnrweb.firebaseapp.com',
    databaseURL: 'https://ctnrweb.firebaseio.com',
    storageBucket: 'ctnrweb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiBv92ZXm40_dRN1xqyxG0FRDfCmQJ1zI',
    appId: '1:1030432137825:android:727ada316d6221cd8bc020',
    messagingSenderId: '1030432137825',
    projectId: 'ctnrweb',
    databaseURL: 'https://ctnrweb.firebaseio.com',
    storageBucket: 'ctnrweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsHDKCnZtKOGZxAJif9zh912AunEr7OFQ',
    appId: '1:1030432137825:ios:8f1991b80fa802f98bc020',
    messagingSenderId: '1030432137825',
    projectId: 'ctnrweb',
    databaseURL: 'https://ctnrweb.firebaseio.com',
    storageBucket: 'ctnrweb.appspot.com',
    iosClientId: '1030432137825-ctu9abcjntmie1k2t28ggrs146g9tq8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctnrweb',
  );
}
